### ISSUE TITLE
OK Google hotword detection doesn't work

### ISSUE THREAD

**Issue by abear1538** [TEAM-Gummy/android_device_oppo_find7#1]
When Google Now / Google Now Launcher is installed and the prompt "Say OK Google" is displayed on the screen, the device does not respond to "OK Google".

If the mic button on the display is pressed, the device hears and responds to voice commands.

Device: Find 7 US LTE

**Comment by papi92** [comment]
Please submit your fix to review.gummyrom.com thanks

**Comment by abear1538** [comment]
> submit your fix

Your request assumes that:
1. I have a fix, which I don't, because I'm not a programmer. I'm a user reporting an issue. I assumed that's what the "report issue" feature was to be used for.
2. It's not acceptable to report problems, as a user.

If both of these are true, do I:
1. Not report problems at all. Simply wait and hope that someone eventually notices the problem.
2. Use a different method to report the problem.

**Comment by dhacker29** [comment]
I'll test tonight. It was working on the last build I was using. What's the date of your build?

**Comment by abear1538** [comment]
The build date is 7-6-2014.

Thank you for testing, but that doesn't answer my question.

I don't want to annoy you by submitting bugs here if it's the wrong place.

Should I report problems here or somewhere else?

**Comment by kejar31** [comment]
Works just fine here

**Comment by abear1538** [comment]
Still doesn't work on the July 12 build.
Are you using model x9076?

**Comment by dhacker29** [comment]
Are you talking about the google everywhere? For me it works in google now
but the google everywhere it's not launching just beeps

**Comment by dhacker29** [comment]
Take that back everywhere is working also. So not sure maybe the gapps you
are using?

**Comment by abear1538** [comment]
I'll describe the situation:

I have the Google Launcher installed.

On the home screen, at the top, it says "Say OK Google".

You should be able to say "OK Google" and get a response indicating you can go ahead with a voice command.

It should also work when you swipe left to Google Now.

However, it doesn't work in either place.

Also, when I turn on "On Any Screen" I am prompted to say "OK Google" 3 times.

But the phone never hears me say OK Google even once.

This is the gapps package I'm using:
http://forum.xda-developers.com/showthread.php?t=2397942

I am using the "Micro Modular" package for Android 4.4.4.

**Comment by dhacker29** [comment]
I don't know other than a full data wipe it's working in Google launcher as well for me

**Comment by kejar31** [comment]
Working fine here.. Try the cm gapps

**Comment by abear1538** [comment]
That works; however, Google Play Store immediately wants to upgrade Google Search and as soon as it does the hot word detection stops working.

Are using an older version of Google Search?

**Comment by kejar31** [comment]
I am def using the latest search and google home... Not having an issue.. Did you make sure to wipe the system before installing gummy and  the gapps I recommended

**Comment by abear1538** [comment]
Yes. Since no one else is having this issue I'm closing it.

**Comment by cphelps76** [comment]
you need to address issues with google apps to google, not gummy

**Comment by abear1538** [comment]
If you want to make a snarky comment about my inadequacy at filing bug reports you should do it before the issue has been closed by the user.

**Comment by abear1538** [comment]
FYI: I figured out what causes this problem.
If any application which uses Notification Access is installed Google Hotword Detection stops working, even if Notification Access is not installed for those apps.

Uninstalling Pushbullet and Qualcomm Toq (two apps that use Notification Access) immediately fixed the problem.
