### ISSUE TITLE
Disable carrier display does nothing

### ISSUE THREAD

**Issue by abear1538** [TEAM-Gummy/android_device_oppo_find7#4]
Disable carrier display in Gummy Settings does not disable carrier display.

This is bad user experience because if the user turns off an option they expect it to switch off.

**Comment by cphelps76** [comment]
this feature is for disabling carrier label in notification drawer, which works fine

**Comment by abear1538** [comment]
Probably you should label the feature in a way that is more descriptive of what it does.

**Comment by ghost** [comment]
Issue was closed a year ago....Why do I keep getting these notifs...haha
